/* Generated By:JavaCC: Do not edit this line. LughatDadConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface LughatDadConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int MUTA_GHAYYER = 6;
  /** RegularExpression Id. */
  int ITBA3 = 7;
  /** RegularExpression Id. */
  int ETHA = 8;
  /** RegularExpression Id. */
  int WA_ELLA = 9;
  /** RegularExpression Id. */
  int BAYNAMA = 10;
  /** RegularExpression Id. */
  int SAH = 11;
  /** RegularExpression Id. */
  int KHATA = 12;
  /** RegularExpression Id. */
  int ARABIC_IDENTIFIER = 13;
  /** RegularExpression Id. */
  int ARABIC_LETTER = 14;
  /** RegularExpression Id. */
  int DIGIT = 15;
  /** RegularExpression Id. */
  int NUMBER = 16;
  /** RegularExpression Id. */
  int STRING = 17;
  /** RegularExpression Id. */
  int PLUS = 18;
  /** RegularExpression Id. */
  int MINUS = 19;
  /** RegularExpression Id. */
  int MULTIPLY = 20;
  /** RegularExpression Id. */
  int DIVIDE = 21;
  /** RegularExpression Id. */
  int ASSIGN = 22;
  /** RegularExpression Id. */
  int GT = 23;
  /** RegularExpression Id. */
  int LT = 24;
  /** RegularExpression Id. */
  int EQ = 25;
  /** RegularExpression Id. */
  int NEQ = 26;
  /** RegularExpression Id. */
  int GTE = 27;
  /** RegularExpression Id. */
  int LTE = 28;
  /** RegularExpression Id. */
  int LPAREN = 29;
  /** RegularExpression Id. */
  int RPAREN = 30;
  /** RegularExpression Id. */
  int LBRACE = 31;
  /** RegularExpression Id. */
  int RBRACE = 32;
  /** RegularExpression Id. */
  int SEMICOLON = 33;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<token of kind 5>",
    "\"\\u0645\\u062a\\u063a\\u064a\\u0631\"",
    "\"\\u0627\\u0637\\u0628\\u0639\"",
    "\"\\u0625\\u0630\\u0627\"",
    "\"\\u0648\\u0625\\u0644\\u0627\"",
    "\"\\u0628\\u064a\\u0646\\u0645\\u0627\"",
    "\"\\u0635\\u062d\"",
    "\"\\u062e\\u0637\\u0623\"",
    "<ARABIC_IDENTIFIER>",
    "<ARABIC_LETTER>",
    "<DIGIT>",
    "<NUMBER>",
    "<STRING>",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"=\"",
    "\">\"",
    "\"<\"",
    "\"==\"",
    "\"!=\"",
    "\">=\"",
    "\"<=\"",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "<SEMICOLON>",
  };

}
